package nl.ithelden.model.ndtrc;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.ArrayList;
import java.util.List;
import nl.ithelden.model.util.ToStringBuilder;

/**
 * Represents SEO metadata for a TRC item, including per-language meta tags,
 * social sharing configuration (Open Graph + Twitter Cards), canonical URL settings,
 * and sitemap directives.
 *
 * <h3>Overview</h3>
 * <p>SEO metadata helps search engines understand and display content correctly in search results
 * and ensures content looks professional when shared on social media platforms.</p>
 *
 * <h3>Structure</h3>
 * <ul>
 *   <li><strong>seoDetails</strong> - Per-language SEO content (meta title, description, OG image/type, Twitter card type)</li>
 *   <li><strong>canonical</strong> - Canonical URL configuration to avoid duplicate content issues</li>
 *   <li><strong>sitemap</strong> - XML sitemap inclusion and priority settings</li>
 * </ul>
 *
 * <h3>Design Decisions</h3>
 * <ul>
 *   <li><strong>No separate OpenGraph/TwitterCard objects.</strong> Social sharing title and description
 *       are intentionally reused from metaTitle/metaDescription. In practice these are almost always
 *       identical, so separate title/description fields per platform would just create redundancy.
 *       Only platform-specific fields (image, OG type, Twitter card type) are stored separately.</li>
 *   <li><strong>No focus keyphrase or secondary keyphrases.</strong> These are editor-time analysis
 *       concepts (as seen in Yoast/Rankmath) used to score content quality in real time. They don't
 *       need to be persisted in the domain model since they have no effect on the rendered output.</li>
 *   <li><strong>No template placeholders.</strong> Template-based title/description generation
 *       (e.g. "{title} in {city}") is a rendering concern handled by API consumers, not stored
 *       in the model. The metaTitle and metaDescription fields hold final, resolved values.</li>
 *   <li><strong>No schema.org configuration.</strong> Schema.org JSON-LD is a rendering concern.
 *       All data needed for structured data (dates, location, prices, performers, images, contact)
 *       already exists in TRCItem's existing blocks (Calendar, Location, PriceElement, Performer,
 *       File, Contactinfo). The schema type can be inferred from the entity type and item categories.
 *       JSON-LD generation belongs in the API layer, not in the domain model.</li>
 * </ul>
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class SeoMetadata {

    private List<SeoDetail> seoDetails = new ArrayList<>();
    private CanonicalConfig canonical;
    private boolean overwriteDefaults = false;

    /**
     * Schema.org JSON-LD string, generated by the API from existing TRCItem data.
     * This is a read-only output field — not stored, but computed and returned in API responses
     * so consumers can embed it directly in a {@code <script type="application/ld+json">} tag.
     *
     * <h4>How it works</h4>
     * <p>The API assembles JSON-LD from existing TRCItem blocks using this mapping:</p>
     * <ul>
     *   <li>TRCItemDetail -> name, description</li>
     *   <li>Calendar -> startDate, endDate, eventStatus</li>
     *   <li>Location -> address, geo coordinates</li>
     *   <li>PriceElement -> offers (price, currency, availability)</li>
     *   <li>Performer -> performer list</li>
     *   <li>File (main image) -> image</li>
     *   <li>Contactinfo -> organizer</li>
     *   <li>EntityType / TRCItemCategories -> @type (Event, Place, Restaurant, Museum, etc.)</li>
     * </ul>
     *
     * <h4>Example — Event</h4>
     * <pre>{@code
     * {
     *   "@context": "https://schema.org",
     *   "@type": "Event",
     *   "name": "Canal Cruise Amsterdam",
     *   "startDate": "2026-03-01T10:00",
     *   "location": {
     *     "@type": "Place",
     *     "name": "Rederij Kooij",
     *     "address": {
     *       "@type": "PostalAddress",
     *       "streetAddress": "Rokin 125",
     *       "addressLocality": "Amsterdam"
     *     }
     *   },
     *   "offers": {
     *     "@type": "Offer",
     *     "price": "16.00",
     *     "priceCurrency": "EUR",
     *     "availability": "https://schema.org/InStock"
     *   },
     *   "image": "https://example.com/cruise.jpg",
     *   "organizer": {
     *     "@type": "Organization",
     *     "name": "I amsterdam",
     *     "url": "https://iamsterdam.com"
     *   },
     *   "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
     *   "eventStatus": "https://schema.org/EventScheduled"
     * }
     * }</pre>
     *
     * <h4>Example — Restaurant</h4>
     * <pre>{@code
     * {
     *   "@context": "https://schema.org",
     *   "@type": "Restaurant",
     *   "name": "Restaurant De Kas",
     *   "address": {
     *     "@type": "PostalAddress",
     *     "streetAddress": "Kamerlingh Onneslaan 3",
     *     "postalCode": "1097 DE",
     *     "addressLocality": "Amsterdam"
     *   },
     *   "geo": {
     *     "@type": "GeoCoordinates",
     *     "latitude": 52.356,
     *     "longitude": 4.924
     *   },
     *   "image": "https://example.com/dekas.jpg"
     * }
     * }</pre>
     */
    private String schemaOrgJsonLd;

    public List<SeoDetail> getSeoDetails() {
        return seoDetails;
    }

    public void setSeoDetails(List<SeoDetail> seoDetails) {
        this.seoDetails = seoDetails;
    }

    public CanonicalConfig getCanonical() {
        return canonical;
    }

    public void setCanonical(CanonicalConfig canonical) {
        this.canonical = canonical;
    }

    public boolean getOverwriteDefaults() {
        return overwriteDefaults;
    }

    public boolean isOverwriteDefaults() {
        return overwriteDefaults;
    }

    public void setOverwriteDefaults(boolean overwriteDefaults) {
        this.overwriteDefaults = overwriteDefaults;
    }

    public String getSchemaOrgJsonLd() {
        return schemaOrgJsonLd;
    }

    public void setSchemaOrgJsonLd(String schemaOrgJsonLd) {
        this.schemaOrgJsonLd = schemaOrgJsonLd;
    }

    /**
     * Per-language SEO content including meta tags and social sharing configuration.
     *
     * <p>For social sharing (Open Graph / Twitter Cards), the metaTitle and metaDescription
     * are reused as the social sharing title and description. Only the image and type
     * need to be configured separately.</p>
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class SeoDetail {
        private String lang;
        private String metaTitle;
        private String metaDescription;

        // Open Graph (Facebook, LinkedIn, WhatsApp)
        private String ogImageUrl;
        private String ogImageAlt;
        private String ogType; // temp

        // Twitter/X Card
        private TwitterCardType twitterCardType;
        private String twitterImageUrl;
        private String twitterImageAlt;

        public String getLang() {
            return lang;
        }

        public void setLang(String lang) {
            this.lang = lang;
        }

        public String getMetaTitle() {
            return metaTitle;
        }

        public void setMetaTitle(String metaTitle) {
            this.metaTitle = metaTitle;
        }

        public String getMetaDescription() {
            return metaDescription;
        }

        public void setMetaDescription(String metaDescription) {
            this.metaDescription = metaDescription;
        }

        public String getOgImageUrl() {
            return ogImageUrl;
        }

        public void setOgImageUrl(String ogImageUrl) {
            this.ogImageUrl = ogImageUrl;
        }

        public String getOgImageAlt() {
            return ogImageAlt;
        }

        public void setOgImageAlt(String ogImageAlt) {
            this.ogImageAlt = ogImageAlt;
        }

        public String getOgType() {
            return ogType;
        }

        public void setOgType(String ogType) {
            this.ogType = ogType;
        }

        public TwitterCardType getTwitterCardType() {
            return twitterCardType;
        }

        public void setTwitterCardType(TwitterCardType twitterCardType) {
            this.twitterCardType = twitterCardType;
        }

        public String getTwitterImageUrl() {
            return twitterImageUrl;
        }

        public void setTwitterImageUrl(String twitterImageUrl) {
            this.twitterImageUrl = twitterImageUrl;
        }

        public String getTwitterImageAlt() {
            return twitterImageAlt;
        }

        public void setTwitterImageAlt(String twitterImageAlt) {
            this.twitterImageAlt = twitterImageAlt;
        }

        public enum OGType {
            event, place, article, organization;

            // Groovy gives every enum these members; kept so the 1.x API is unchanged.
            public static final OGType MIN_VALUE = event;
            public static final OGType MAX_VALUE = organization;

            public OGType next() {
                OGType[] values = values();
                int ordinal = ordinal() + 1;
                return values[ordinal >= values.length ? 0 : ordinal];
            }

            public OGType previous() {
                OGType[] values = values();
                int ordinal = ordinal() - 1;
                return values[ordinal < 0 ? values.length - 1 : ordinal];
            }
        }

        public enum TwitterCardType {
            summary, summary_large_image, app, player;

            // Groovy gives every enum these members; kept so the 1.x API is unchanged.
            public static final TwitterCardType MIN_VALUE = summary;
            public static final TwitterCardType MAX_VALUE = player;

            public TwitterCardType next() {
                TwitterCardType[] values = values();
                int ordinal = ordinal() + 1;
                return values[ordinal >= values.length ? 0 : ordinal];
            }

            public TwitterCardType previous() {
                TwitterCardType[] values = values();
                int ordinal = ordinal() - 1;
                return values[ordinal < 0 ? values.length - 1 : ordinal];
            }
        }

        @Override
        public String toString() {
            return new ToStringBuilder(SeoDetail.class, this)
                    .add("lang", lang)
                    .add("metaTitle", metaTitle)
                    .add("metaDescription", metaDescription)
                    .add("ogImageUrl", ogImageUrl)
                    .add("ogImageAlt", ogImageAlt)
                    .add("ogType", ogType)
                    .add("twitterCardType", twitterCardType)
                    .add("twitterImageUrl", twitterImageUrl)
                    .add("twitterImageAlt", twitterImageAlt)
                    .build();
        }
    }

    /**
     * Canonical URL configuration to avoid duplicate content issues across partner sites.
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class CanonicalConfig {
        private String canonicalUrl;

        public String getCanonicalUrl() {
            return canonicalUrl;
        }

        public void setCanonicalUrl(String canonicalUrl) {
            this.canonicalUrl = canonicalUrl;
        }

        @Override
        public String toString() {
            return new ToStringBuilder(CanonicalConfig.class, this)
                    .add("canonicalUrl", canonicalUrl)
                    .build();
        }
    }

    @Override
    public String toString() {
        return new ToStringBuilder(SeoMetadata.class, this)
                .add("seoDetails", seoDetails)
                .add("canonical", canonical)
                .add("overwriteDefaults", overwriteDefaults)
                .add("schemaOrgJsonLd", schemaOrgJsonLd)
                .build();
    }
}
