package nl.ithelden.model.ndtrc

import com.fasterxml.jackson.annotation.JsonInclude
import groovy.transform.ToString

/**
 * Represents SEO metadata for a TRC item, including per-language meta tags,
 * social sharing configuration (Open Graph + Twitter Cards), canonical URL settings,
 * and sitemap directives.
 *
 * <h3>Overview</h3>
 * <p>SEO metadata helps search engines understand and display content correctly in search results
 * and ensures content looks professional when shared on social media platforms.</p>
 *
 * <h3>Structure</h3>
 * <ul>
 *   <li><strong>seoDetails</strong> - Per-language SEO content (meta title, description, OG image/type, Twitter card type)</li>
 *   <li><strong>canonical</strong> - Canonical URL configuration to avoid duplicate content issues</li>
 *   <li><strong>sitemap</strong> - XML sitemap inclusion and priority settings</li>
 * </ul>
 *
 * <h3>Design Decisions</h3>
 * <ul>
 *   <li><strong>No separate OpenGraph/TwitterCard objects.</strong> Social sharing title and description
 *       are intentionally reused from metaTitle/metaDescription. In practice these are almost always
 *       identical, so separate title/description fields per platform would just create redundancy.
 *       Only platform-specific fields (image, OG type, Twitter card type) are stored separately.</li>
 *   <li><strong>No focus keyphrase or secondary keyphrases.</strong> These are editor-time analysis
 *       concepts (as seen in Yoast/Rankmath) used to score content quality in real time. They don't
 *       need to be persisted in the domain model since they have no effect on the rendered output.</li>
 *   <li><strong>No template placeholders.</strong> Template-based title/description generation
 *       (e.g. "{title} in {city}") is a rendering concern handled by API consumers, not stored
 *       in the model. The metaTitle and metaDescription fields hold final, resolved values.</li>
 *   <li><strong>No schema.org configuration.</strong> Schema.org JSON-LD is a rendering concern.
 *       All data needed for structured data (dates, location, prices, performers, images, contact)
 *       already exists in TRCItem's existing blocks (Calendar, Location, PriceElement, Performer,
 *       File, Contactinfo). The schema type can be inferred from the entity type and item categories.
 *       JSON-LD generation belongs in the API layer, not in the domain model.</li>
 * </ul>
 */
@ToString(includeNames = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
class SeoMetadata {

    List<SeoDetail> seoDetails = []
    CanonicalConfig canonical

    /**
     * Schema.org JSON-LD string, generated by the API from existing TRCItem data.
     * This is a read-only output field — not stored, but computed and returned in API responses
     * so consumers can embed it directly in a {@code <script type="application/ld+json">} tag.
     *
     * <h4>How it works</h4>
     * <p>The API assembles JSON-LD from existing TRCItem blocks using this mapping:</p>
     * <ul>
     *   <li>TRCItemDetail -> name, description</li>
     *   <li>Calendar -> startDate, endDate, eventStatus</li>
     *   <li>Location -> address, geo coordinates</li>
     *   <li>PriceElement -> offers (price, currency, availability)</li>
     *   <li>Performer -> performer list</li>
     *   <li>File (main image) -> image</li>
     *   <li>Contactinfo -> organizer</li>
     *   <li>EntityType / TRCItemCategories -> @type (Event, Place, Restaurant, Museum, etc.)</li>
     * </ul>
     *
     * <h4>Example — Event</h4>
     * <pre>{@code
     * {
     *   "@context": "https://schema.org",
     *   "@type": "Event",
     *   "name": "Canal Cruise Amsterdam",
     *   "startDate": "2026-03-01T10:00",
     *   "location": {
     *     "@type": "Place",
     *     "name": "Rederij Kooij",
     *     "address": {
     *       "@type": "PostalAddress",
     *       "streetAddress": "Rokin 125",
     *       "addressLocality": "Amsterdam"
     *     }
     *   },
     *   "offers": {
     *     "@type": "Offer",
     *     "price": "16.00",
     *     "priceCurrency": "EUR",
     *     "availability": "https://schema.org/InStock"
     *   },
     *   "image": "https://example.com/cruise.jpg",
     *   "organizer": {
     *     "@type": "Organization",
     *     "name": "I amsterdam",
     *     "url": "https://iamsterdam.com"
     *   },
     *   "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
     *   "eventStatus": "https://schema.org/EventScheduled"
     * }
     * }</pre>
     *
     * <h4>Example — Restaurant</h4>
     * <pre>{@code
     * {
     *   "@context": "https://schema.org",
     *   "@type": "Restaurant",
     *   "name": "Restaurant De Kas",
     *   "address": {
     *     "@type": "PostalAddress",
     *     "streetAddress": "Kamerlingh Onneslaan 3",
     *     "postalCode": "1097 DE",
     *     "addressLocality": "Amsterdam"
     *   },
     *   "geo": {
     *     "@type": "GeoCoordinates",
     *     "latitude": 52.356,
     *     "longitude": 4.924
     *   },
     *   "image": "https://example.com/dekas.jpg"
     * }
     * }</pre>
     */
    String schemaOrgJsonLd

    /**
     * Per-language SEO content including meta tags and social sharing configuration.
     *
     * <p>For social sharing (Open Graph / Twitter Cards), the metaTitle and metaDescription
     * are reused as the social sharing title and description. Only the image and type
     * need to be configured separately.</p>
     */
    @ToString(includeNames = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    static class SeoDetail {
        String lang
        String metaTitle
        String metaDescription

        // Open Graph (Facebook, LinkedIn, WhatsApp)
        String ogImageUrl
        String ogImageAlt
        OGType ogType

        // Twitter/X Card
        TwitterCardType twitterCardType

        enum OGType { event, place, article, organization }
        enum TwitterCardType { summary, summary_large_image }
    }

    /**
     * Canonical URL configuration to avoid duplicate content issues across partner sites.
     */
    @ToString(includeNames = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    static class CanonicalConfig {
        String canonicalUrl
    }
}
